### ISSUE TITLE
Add a mode for digital time display

### ISSUE THREAD

**Issue by walmik** [walmik/timer.jquery#1]
Add a digital mode for displaying time, like this
1. 00:34
2. 00:09:23
3. 01:01:50:30

**Comment by yeruizhi** [comment]
This functionality is very helpful. Has it been done? Thanks.

**Comment by yeruizhi** [comment]
I read your code and find that function.  I add another formatting function that output time in fixed "hh:mm:ss" format, like "00:00:01" .

**Comment by walmik** [comment]
This functionality has not been implemented as yet. Please do feel free to submit a PR in case you do implement it :)

**Comment by walmik** [comment]
Closing this issue in favor of issue #36
