### ISSUE TITLE
Regressive Timer

### ISSUE THREAD

**Issue by mahousenshi** [walmik/timer.jquery#25]
Hello!

It's will be great if this plugin can suport a regresive counter.

Thank for this simple plugin.

**Comment by walmik** [comment]
Thanks for your comments and suggestions. Can you please tell me how do you mean when you say regressive counter? Do you mean like a regular digital display as opposed to pretty display?

**Comment by walmik** [comment]
Possibly a dupe of https://github.com/walmik/timer.jquery/issues/1

**Comment by mahousenshi** [comment]
Like a countdown clock.

**Comment by walmik** [comment]
Re-opening this issue

**Comment by ryanv09** [comment]
I have a simple solution for this until a better one is pushed.

In the render function, replace:


`$el[display](secondsToTime(totalSeconds));`

with:

<pre>
`if (options.countdown && duration > 0)
{
	$el[display](secondsToTime(duration - totalSeconds));
}
else
{
	$el[display](secondsToTime(totalSeconds));
}`
</pre>

and then call it like this:

`$("selector").timer({duration:60, countdown:true});`

**Comment by walmik** [comment]
That s a good idea. Please feel free to submit a PR if it works and passes currently written tests. If possible add a test for it too.
