### ISSUE TITLE
Paused Status

### ISSUE THREAD

**Issue by mahousenshi** [walmik/timer.jquery#26]
Hello!

It's will be great if the timer can send a "paused" status.

Thanks!

**Comment by walmik** [comment]
Hello there, the timer does have a 'pause' state. You can trigger that on a running timer by doing

`$('#timerDiv').timer('pause');`

You can demo this functionality here: http://jquerytimer.com/

**Comment by mahousenshi** [comment]
I'm doing a chronometer using no buttons using a click in the timer to start/pause it but i didn't know if there's a timer object where or it's just paused timer i have to use a dummy class to know this.

**Comment by walmik** [comment]
Do you mean something like a 'state' method, which will return if the timer is running, stopped or paused?

**Comment by mahousenshi** [comment]
Yes.

**Comment by shantanuthatte** [comment]
How about using `$el.data('state', state)` in `start()`, `stop()`, etc ... ??

**Comment by walmik** [comment]
That s a good idea!

**Comment by walmik** [comment]
Added this functionality in 1ce2d6a61f9b77afeeac982e9a9d318fdfa81042
