### ISSUE TITLE
Callback issue when seconds parameter is also passed along with duration parameter

### ISSUE THREAD

**Issue by akhilsikri** [walmik/timer.jquery#28]
hi

I found an issue with the callback if we resume the timer from a preset value.

```
$('#timerId').timer({
    seconds: 100
    duration: '3s',
    callback: function() {
      console.log('Notify me every 3 seconds');
    },
    repeat: true //repeatedly calls the callback you specify
});
```
I was able to fix the issue by updating the duration with the increment of initial seconds.
```
		if (options.duration) {
		  duration = options.duration = timeToSeconds(options.duration);
		  // Akhil - fix for duration and initial seconds
		  if (options.seconds) {
			var duration_time = options.duration + options.seconds;
			duration = duration_time = timeToSeconds(duration_time);	
		  }
		} 
```

I thought it might be helpful if someone else has similar requirement.

**Comment by walmik** [comment]
Thanks for catching this! I have added a fix for this in a slightly different way (adhering to existing code) and committed it. Please feel free to submit a PR next time :)

**Comment by shantanuthatte** [comment]
I am not able to recreate the issue.

Problem would be if seconds > duration, then the callback is never called
