### ISSUE TITLE
Customise display so you can show the clock in format hh:mm:ss (or just mm:ss)

### ISSUE THREAD

**Issue by Allmythings1066** [walmik/timer.jquery#29]
Can someone help please - I would like to customise the display so the hh:mm:ss (or just mm:ss) are always displayed ie 00:00. I would also like to hide the sec or min text that is appended to the clock display
Any help would be really appreciated

**Comment by walmik** [comment]
This is a dupe of issue #1 and is under consideration.

Having said that, here s a quick implementation you can try. In the plugin JS itself, add a function right after the function `secondsToTime` like this:

```
function secondsToHhMmSs(totalSeconds) {
	var hours = parseInt( totalSeconds / 3600 ) % 24,
		minutes = parseInt( totalSeconds / 60 ) % 60,
		seconds = totalSeconds % 60,
		result = (hours < 10 ? "0" + hours : hours) + ":" + (minutes < 10 ? "0" + minutes : minutes) + ":" + (seconds  < 10 ? "0" + seconds : seconds);

	return result;
}
```

And in the function `render()` (currently on line 71) change the following line
`$el[display](secondsToTime(totalSeconds));`

to

`$el[display](secondsToHhMmSs(totalSeconds));`

Lemme know if that works for you. If not then I ll implement this soon :)

**Comment by Allmythings1066** [comment]
Thanks walmik - I'll give it a go and get back to you.  Can you recommend a tool for generated the minified code?

**Comment by Allmythings1066** [comment]
Hi Walmik, your code worked like a treat! Thanks very much :+1:

**Comment by walmik** [comment]
You are very welcome :)
