### ISSUE TITLE
Counting down

### ISSUE THREAD

**Issue by fmsolbakken** [walmik/timer.jquery#42]
Very nice plugin!
Could we also have a counting down option?
Need to start at 60s and counting down to 0.

**Comment by walmik** [comment]
Hi there, Thanks for your comments!

There is a countdown option. All you have to do is specify the `duration` and the `countdown` option as follows:
```
$('#timerDiv').timer({
    countdown: true,
    duration: '3m40s'    // This will start the countdown from 3 mins 40 seconds
});
```
