### ISSUE TITLE
Seconds count slightly innacurate

### ISSUE THREAD

**Issue by spedroq** [walmik/timer.jquery#45]
To replicate it, is a matter of letting it run for about 5minutes and you will notice that it will be off by about 15 to 20 seconds. (it will count faster than usual timers)

Thanks for your time and hard work.

Cheers

**Comment by walmik** [comment]
Hi @spedroq 

Thank you for your time and concern regarding the jQuery timer plugin. 

I ran the jQuery timer and I used the Mac OS timer to compare the both. I left it running and took screenshots along the way at durations of 10 seconds, 6 minutes, 11 minutes, 20 minutes and 30 minutes. Here are the screenshots:

*10 sec:*

<img width="131" alt="10sec" src="https://cloud.githubusercontent.com/assets/467030/9255516/c278ce98-419e-11e5-8abd-8b208ac66b68.png">

*6 min:*

<img width="213" alt="6min" src="https://cloud.githubusercontent.com/assets/467030/9255523/c64d373e-419e-11e5-8859-5995bf80e61e.png">

*11 min:*

<img width="144" alt="11min" src="https://cloud.githubusercontent.com/assets/467030/9255530/d5864218-419e-11e5-8193-cbb1f66d2789.png">

*20 min:*

<img width="205" alt="20min" src="https://cloud.githubusercontent.com/assets/467030/9255531/db310f72-419e-11e5-96c1-fbc025354ea1.png">

*30 min:*

<img width="211" alt="30min" src="https://cloud.githubusercontent.com/assets/467030/9255538/df73a87e-419e-11e5-8e65-f826ce87e73d.png">

The timer was accurate at all the times and I was not able to see the issue you described. Can you please provide some more details? Like OS, Browser, the timer that you used to compare with? Screenshots will be awesome too! 

Please try & use system time as the guide for checking accuracy.

Thanks for your time and concern!

**Comment by spedroq** [comment]
Maybe it was the other timer I used that was off... hahah

It was compared vs X-Lite and Eyebeam, since I was using it to track the duration of calls.

If the timer is correct than I could have been wrong. Since I noticed that difference I though I would bring it up.

Thanks for your time and hard work.
Cheers,
Pedro Q

**Comment by walmik** [comment]
No worries, it never hurts to confirm our doubts :) Thanks for your time.
