### ISSUE TITLE
Add Countdown 

### ISSUE THREAD

**Issue by IanCaz** [walmik/timer.jquery#49]
I'm loving this plug-in and it would completely satisfy my needs if it supported counting down from a preset time.  Is this currently possible?  If not, it would make a great enhancement.

**Comment by IanCaz** [comment]
Okay, evidently this IS possible, by using the duration & setting the undocumented option "countdown" to true.

**Comment by walmik** [comment]
Thank you for your observation that `countdown` is undocumented! I will add it in my upcoming overhaul for the demo page of this plugin :)

**Comment by walmik** [comment]
@IanCaz Thank you  for your observation that `countdown` is undocumented! I will add it in my upcoming overhaul for the demo page of this plugin :)
