### ISSUE TITLE
Options being duplicated between different instances of timer

### ISSUE THREAD

**Issue by IanCaz** [walmik/timer.jquery#50]
There appears to be an issue when creating multiple timers, where the "options" from the last instantiated timer, override the values for the previous timers.  The most obvious example of this can be seen in the callback or format.  In the example below, I have two divs, with the id's of timerTest1 & timerTest2.

```
            $("#timerTest1").timer({
                duration: '3s',
                format: '%H:%M:%S',
                callback: function () {
                    $("#timerTest1").css("color", "red");
                    alert("This is the timerTest1 callback");
                }
            });
            $("#timerTest2").timer({
                duration: '5s',
                format: '%M:%S',
                callback: function () {
                    $("#timerTest2").css("color", "green");
                    alert("This is the timerTest2 callback");
                }
            });
```

From digging through the source, it appears that in the "TIMER PROTOTYPE" section, the options object always has the values of the last iteration.

Sample file:
[test.txt](https://github.com/walmik/timer.jquery/files/86368/test.txt)

**Comment by IanCaz** [comment]
Okay, I think I've found the culprit.  I changed the $.extend line in the prototype & modified the secondsToTime to take a timer object as well.  These two changes seem to have "fixed" the issue.
[timer.jquery.js.txt](https://github.com/walmik/timer.jquery/files/87528/timer.jquery.js.txt)

**Comment by walmik** [comment]
Hey @IanCaz Thanks for identifying an issue and finding the fix for the same. Can you please submit a PR for this?

**Comment by IanCaz** [comment]
Alright, I think I finally got it done.  My first time working with Git, so let me know if I need to do something differently.

**Comment by walmik** [comment]
@IanCaz Thank you once again. I ve merged this in, made some minor changes to resolve jscs issues and bumped the version.
