### ISSUE TITLE
A simple example

### ISSUE THREAD

**Issue by sinanerdem** [walmik/timer.jquery#56]
Hello and thank you for this utility.

I am trying to test it. I created a jsfiddle for this:
https://jsfiddle.net/t30Lugfn/
That is really simple, yet I couldnt make it work. Can you comment?

Cheers

**Comment by sinanerdem** [comment]
I think it is about loading external content from this address:
https://raw.githubusercontent.com/walmik/timer.jquery/master/src/timer.jquery.js

When I used my own repository, it worked.

**Comment by walmik** [comment]
Glad it worked it out :)
