### ISSUE TITLE
Minutes and seconds only

### ISSUE THREAD

**Issue by sinanerdem** [walmik/timer.jquery#57]
Is it possible to display a format like: 75:15 ?

I tried %M:%S, but instead of 75:15, it only displays 15:15

**Comment by walmik** [comment]
Thanks for using the plugin and creating an issue toward it's improvement. 

Currently we do not have a method that allows showing 60+ minutes the way you specified. Same applies to seconds as well. But I like this idea! I m open to PRs that implements this as a feature and has test cases to support it.

**Comment by walmik** [comment]
Fixed by @randomAccessMe in https://github.com/walmik/timer.jquery/pull/61
