### ISSUE TITLE
Get seconds into other variable

### ISSUE THREAD

**Issue by uareke** [walmik/timer.jquery#58]
How do I get the second ? I need to show an alert to the User when missing 10 seconds.

**Comment by walmik** [comment]
Sorry for the delay in @uareke, you can get the seconds on a running (or paused) timer by doing
```
var seconds = $('#timerDiv').data('seconds');
```

If you want something to be done at the end of 10 seconds, you can also use the callback attribute of the timer plugin like this,
```
//start a timer & execute a function in 10 seconds
$('#div-id').timer({
    duration: '10s',
    callback: function() {
        alert('Time up!');
    }
});
```

You can even chose to stop the timer on completion of 10 seconds in the same callback. 
```
//start a timer & execute a function in 10 seconds
$('#div-id').timer({
    duration: '10s',
    callback: function() {
        $('#div-id').timer('stop');
        alert('Time up!');
    }
});
```

Hope this helps. Do let me know if you'd like any more information about this plugin and how it can help in your specific use case.
