### ISSUE TITLE
Execute callback when timer is set to zero

### ISSUE THREAD

**Issue by wgpalexander** [walmik/timer.jquery#59]
Hi guys,

Great script here - very useful. I'm having a slight issue with it - allow me to explain.

I have a series of timed events each on triggered after another (think about a triathlon style thing where you have a run, a cycle and a swim so each one is timed in sequence). 

I have structured this by having a series of timers 'nested' within the callbacks.

My issue is that some users may want one phase (e.g. the cycle in the above example) to be skipped so they set it to a nil value. Unfortunately loading zero into the timer doesn't then trigger the callback and the don't get the opportunity to do the swim (in the above example.)

I have tried loading a fractional second (0.001s) into the function but this seems to round to 1 second so is not really suitable for exact timings.

Do you guys have anything you can suggest to help me out here? I really just need to skip to the callback.

`function startTimer(duration, cbk) {

    // Load variable dur based on duration input
    var dur = duration;

    if(dur == 0)
    {
        // If the item has a nil duration need to make timer stop at 0
        // and then somehow callback to continue the function loops

        $('#Elapsed').timer({

            seconds: 0,

            duration: '0s',      // This doesn't fire the callback, 0.001s time delay is too high though
                
            callback: cbk     // Needed to continue the script

        }); // End Elapsed
    }
    else
    {
        // Set the duration for the timer using the input
        var d = "'" + duration + "s'";

        // Now need to start the timer
        // Use the jQuery timer plugin code

        $('#Elapsed').timer({

            seconds: 0,

            duration: d,
                
            callback: cbk

        }); // End Elapsed

    } // End if

} // End startTimer`

Thanks!
Wayne

**Comment by walmik** [comment]
HI Wayne!

Thanks for using this plugin! About your query, in case the duration is 0, can you not directly call the callback function? So something like,

```
function startTimer(duration, cbk) {
	// Early return and callback in case duration is 0
	if(duration === 0) {
		return cbk();
	}

	// Use jQuery timer to defer cbk
	$('#Elapsed').timer({
		duration: duration + 's',
		callback: cbk
	});
} 
```

Lemme know if that can work in your specific use case. If not, we can go into it further :)

**Comment by wgpalexander** [comment]
Hi Walmik, firstly thanks for the prompt response. As you can probably tell I'm learning Javascript so thanks for your patience! Your example of simply returning the callback works - not sure why I didn't think of that. 

For info the default "Time Up!" alert for countdowns is a touch invasive - maybe in future it could be a property option like duration, callback etc.? As it stands I just commented the alert out in the JS file and it works brilliantly.

**Comment by walmik** [comment]
You re very welcome Wayne :) 
About the alert being used as a sample callback, I agree with you. I guess I just wanted to visually demonstrate how the callback can be used. I reckon anybody wanting to use that feature will have their own custom function to overwrite it with anyway.
