### ISSUE TITLE
Timer problem Reset

### ISSUE THREAD

**Issue by AlexAraujoBr** [walmik/timer.jquery#62]
I need a help , when applying reset the timer displays error , showing a strange time .

![timer](https://cloud.githubusercontent.com/assets/19329223/15218663/506e2dc8-1837-11e6-949a-4afd66108054.jpg)

**Comment by walmik** [comment]
Thank you for using the plugin and filing this issue. This contributes to the overall improvement of this plugin :) Can you please provide the exact steps to reproduce the issue? Also can you keep your console open while performing the steps and share the console contents in case you see some error in there as well?

**Comment by AlexAraujoBr** [comment]
Example:

`<!DOCTYPE html>
<html>
    <head>
        <title>Reset Timer</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="JS/jquery-1.12.0.js" type="text/javascript"></script>
        <script src="JS/timerjquery.js" type="text/javascript"></script>
    <script type="text/javascript">
       $(function (e) {
          $('#DT').timer({
             format: '%H:%M:%S'  
          });          
          
          
          $(document).on('click','#bnt', function(){
              $('#DT').timer('reset');
          });
          
       });
        
    </script>  
    </head>
 
    <body>
        <p>
            <div id="DT"> </div>
        </p>
        <button type="button" id="bnt" >&nbsp;Reset Timer</button>
    </body>
</html>
`

**Comment by AlexAraujoBr** [comment]
I got doing a "workaround". I´m just modify "resetTimer" function.

> 	function resetTimer(timer) {
		var element = timer.element;
                stopTimerInterval(timer);
		timer.options.removeTimer.bind(timer).call();
		$(element).data('plugin_' + pluginName, 0);
		$(element).data('seconds', 0);
		$(element).data('state', 0);
                startTimerInterval(timer);
                //stopTimerInterval(timer);
		//$(element).data('seconds', 0);
		//$(element).data('totalSeconds', 0);
		//$(element).data('startTime', 0);
		//$(element).data('state', TIMER_STOPPED);
		$(element).data('duration', timer.options.duration);
		timer.options.resetTimer.bind(timer).call();
	}
>

**Comment by walmik** [comment]
Thanks for fixing it, this looks good! Can you please submit a PR for this?

**Comment by walmik** [comment]
Hi @AlexAraujoBr 

I think something seems funky. I was updating the Develop branch locally to match the recent merges in Master and it shows as if your PR got merged! Can you please check if your changes are in there? Also another thing is, I dont see a fork of this repo in your Github. Can you please tell me how you created the PR?

**Comment by walmik** [comment]
Fixed in https://github.com/walmik/timer.jquery/pull/63
Thanks to @AlexAraujoBr
