### ISSUE TITLE
In countdown timer, pause/resume functionality not working properly.

### ISSUE THREAD

**Issue by jitendrapawar** [walmik/timer.jquery#67]
If we set a countdown timer of 20 sec & paused it at 15 sec, it stops but on resuming it again after 5 sec, it starts from 10 sec instead of 15 sec.

**Comment by walmik** [comment]
@jitendrapawar Thanks for noting this issue! I will look into it shortly.

**Comment by walmik** [comment]
@jitendrapawar I ve fixed this issue in v0.5.2. Can you please confirm? You can download the updated timer plugin: https://raw.githubusercontent.com/walmik/timer.jquery/master/dist/timer.jquery.min.js
