### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by lemonbuzz** [walmik/timer.jquery#69]
I am trying to use this plugin..But it throws me this error in the console:

"Uncaught SyntaxError: Unexpected token import" @ line 2 in Timer.js

I don't know whats wrong...

I don't have a very specific or different working tree...

Project/
├── action
│   ├── CommonAction.php
│   ├── DAO
│   │   ├── Connection.php
│   │   ├── dbInfo.php
│   │   └── UserDAO.php
│   └── IndexAction.php
├── index.php
├── js
│   ├── constants.js
│   ├── index.js
│   ├── Timer.js
│   ├── util.js
│   └── utils.js
└── stylesheets
    └── style.css

Some help would be cool :D

**Comment by walmik** [comment]
Hi @lemonbuzz I think you are referencing the ES6 class directly. Please use the transpiled `timer.jquery.js` or `timer.jquery.min.js` from the `dist/` folder in this repo. Please let me know if that helps and thanks for using this plugin!

Here is a link in case you wanna take it directly from there:
https://raw.githubusercontent.com/walmik/timer.jquery/master/dist/timer.jquery.min.js

Download and save that in your `js/` folder (remove all the other files there like Timer, constants, utils)

**Comment by lemonbuzz** [comment]
Works!!! Thank you very much for the fast response!

Honestly when i saw the code i was a bit perplexed as I never saw classes like that in JS..only encountered the prototype based "classes"...Mind to explain this? What is the ES6 class?

**Comment by walmik** [comment]
Glad it worked out :)

You are not too far when you say 'prototype based "classes". The 'class' you see in this repo is kinda the same thing. Classes are introduced in ECMAScript 6 and are syntactical sugar over JavaScript's existing prototype-based inheritance.

You can read more here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
