### ISSUE TITLE
你的timer.jquery插件有个问题...Your  timer.jquery  js have a bug...

### ISSUE THREAD

**Issue by huangxinliu** [walmik/timer.jquery#70]
您好，首先我很抱歉不太会讲英语，我在项目中使用你的timer.jquery，发现有个问题，在手机下不支持"Object.assign"，我把它换成"$.extend"就好了。
HI,First I'm sorry I don't speak English,I use your timer.jquery for my project, In the mobile browser not support "Object.assign", Me replace "$.extend" it's ok.

**Comment by walmik** [comment]
Thank you very much @huangxinliu !
I ve updated the plugin to use $.extend. Please do let me know if you still see this issue on mobile.

**Comment by huangxinliu** [comment]
@walmik still have Object.assign on timer.jquery/dist/timer.jquery.js 158 line,   0.0

**Comment by walmik** [comment]
@huangxinliu You are right, there was yet another `Object.assign` in the src itself. I ve removed it now. Can you please verify one last time? Thanks again for your diligence!
