### ISSUE TITLE
hey,guy. your js is not supproting ie8

### ISSUE THREAD

**Issue by wenqinruan** [walmik/timer.jquery#71]

**Comment by wenqinruan** [comment]
forEach is not supporting in ie8, in line 214.
line 55 also has a compatibility issue.

**Comment by walmik** [comment]
@wenqinruan Thank you for noting this issue. I can substitute `forEach` with a `for` loop if that is the only thing required for supporting iE 8.

But you mentioned line 55 has a compatibility issue. Can you please clarify a bit more?

**Comment by walmik** [comment]
I think the other compatibility issue was Date.now (IE8 does not support this). Fixed that and forEach dependency in v0.6.5
