### ISSUE TITLE
Displaying a digital clock

### ISSUE THREAD

**Issue by grafikkaos** [walmik/timer.jquery#74]
Is there a quick way of using this plugin to display a clock showing the current time?

Thanks

**Comment by walmik** [comment]
@grafikkaos 
Hi Emmanuel! The jQuery timer plugin does not have a readymade feature to display a digital clock, though you can get hold of the current time in seconds and initialize the timer from that time, like this:

```
var d = new Date();
var todayInSeconds = d.getSeconds() + (60 * d.getMinutes()) + (60 * 60 * d.getHours());

$('#timerDiv').timer({
    seconds: todayInSeconds
});
```

Lemme know if that works for you.
