### ISSUE TITLE
Automatically change to hour format display via callback

### ISSUE THREAD

**Issue by arvi** [walmik/timer.jquery#75]
Hello! :smile: 

Thanks for your great work. I need to change the timer to `"%H:%M:%S"` format when it reached `59:59`. So far I was able to do it but not sure if this is how you'd prefer to be doing it... if yes, then it would be helpful to others if something like this is also added in the documentation examples. If no :smile:  I'd be cool if you share your way of doing it. :smile: 

``` javascript
var callDuration = $('#call-duration');

callDuration.timer({
    duration: '61s', //since 3599 is divisible by 59 or 61
    seconds: 3590, //simulation purposes
    format: '%M:%S',
    callback: function() {

        var total = callDuration.data('seconds');

        if(total === 3599) { //change to hour format (3600 - 1 to prevent display bug)
            this.format = '%H:%M:%S';
        }
    },
    repeat: true //repeatedly call the callback
});
```

**Comment by walmik** [comment]
Hi @arvi 

This looks great, Once I get some time, I m planning to add some recipes for a bunch of things. I ll add this once I get to it.

**Comment by arvi** [comment]
Noted. I've updated the sample above `duration` and `total` upon encountering a bug in the display.

**Comment by walmik** [comment]
Added this to http://jquerytimer.com/
