### ISSUE TITLE
Get %H %M %S

### ISSUE THREAD

**Issue by keshiabrown16** [walmik/timer.jquery#76]
Hi, great plugin :)

Is there anyway to display the time in h m s rather than just displaying total seconds elapsed when using $('#sampleid').data('seconds'); ?

**Comment by shantanuthatte** [comment]
Please see the `format` option in [README](https://github.com/walmik/timer.jquery/blob/master/README.md)

For format syntax, see [Format Syntax](https://github.com/walmik/timer.jquery#format-syntax)

**Comment by keshiabrown16** [comment]
Thanks for the speedy reply but i think you have misunderstood me. I have already set format when calling the timer eg:     
$(".t_header_time").timer({
      format: '%H:%M:%S' 
    });

but when getting the total time elapsed, it only gives you seconds. I want the time elapsed to be h m s.

**Comment by shantanuthatte** [comment]
As a quick solution, you can get the element's text.

In your case,
```javascript
$(".t_header_time").text();
```

**Comment by keshiabrown16** [comment]
Woah. Mind was totally blank, silly me. Thank you!! Again, great plugin :)
