### ISSUE TITLE
Blur event resumes the timer again

### ISSUE THREAD

**Issue by nWidart** [walmik/timer.jquery#77]
Hello,

In current behaviour, once the timer was started + paused, when leaving the input field, it resumes the timer.

Steps to reproduce on jquerytimer.com :

- click "start timer"
- wait couple of seconds
- click "pause"
- Put cursor in input
- Leave the input field

Result: timer resumes

Is there a way to not have this behaviour ? Ie: leaving the input doesn't resume the timer ?

Thanks!

Edit: even with the following code it doesn't resume the timer on blur. 

``` js
$timer.on('blur', function() {
    if(hasTimer) {
        $timer.timer('pause');
    }
});
```

Edit 2:

Found what was causing the blur event: https://github.com/walmik/timer.jquery/blob/master/src/utils.js#L218 but it doesn't look to be configurable.

**Comment by walmik** [comment]
@nWidart 

Thank you for observing this! 

However, please note, this is not a bug/issue in the timer plugin itself. The plugin provides a convenience method for quickly wiring up the focus and blur events on the timer by setting the `editable` property as `true`. This creates these events and it's useful when you don't have any buttons to pause/resume the timer. There was some confusion around this in issue #40 as well.

I'd say this is an issue in jquerytimer.com's implementation of the pause/resume functionality. Looks like it's not in sync with the `editable` property set on the timer.

I will fix this once I get some time. Thanks again!
