### ISSUE TITLE
start time

### ISSUE THREAD

**Issue by ottiauswien** [walmik/timer.jquery#78]
it would be nic, if there would be a start time (in seconds)

**Comment by walmik** [comment]
@ottiauswien There s a start time available (in seconds). For example,

```
$('#timerDiv').timer({
    seconds: 100
});
```
In this example, the timer will start from 100 seconds (displayed as 1:40 min by default). You can use the `format` parameter to customize the display. For instance if you want to display the time in absolute seconds, then initiate the timer like this,
```
$('#timerDiv').timer({
    seconds: 100,
    format: '%T'
});
```

**Comment by ottiauswien** [comment]
thnx. i thouht the timer starts **in** x seconds.... not **with** x seconds.
thnx, perfect.
