### ISSUE TITLE
Causing an Undefined error

### ISSUE THREAD

**Issue by omelsoft** [walmik/timer.jquery#79]
The error has been fixed by adding the jQuery selector '$' as you can see below.

/*! timer.jquery 0.7.0 2017-04-15*/
(function($) {
...
rest of the code
...
} (jQuery));

**Comment by NoCodeMonkey** [comment]
Would be good to get this fix rolled out.

**Comment by walmik** [comment]
Done. Can you please verify @NoCodeMonkey

**Comment by walmik** [comment]
Fixed in 0.7.2
