### ISSUE TITLE
Publish as WebJar

### ISSUE THREAD

**Issue by naXa777** [walmik/timer.jquery#87]
Please publish the latest library version as [WebJar](https://www.webjars.org). So it will be easily accessible from [Gradle](https://gradle.org/) or [Maven](https://maven.apache.org/) in Java projects (and in Scala, Kotlin, Groovy as well).

I think it's a good way to deploy the timer.jquery library.

Example: The Final Countdown ([Github](https://github.com/hilios/jQuery.countdown)) is available at [Maven Central](https://mvnrepository.com/artifact/org.webjars.bower/jquery.countdown).

**Comment by walmik** [comment]
HI @naXa777  I m not well versed with Java but I tried doing this, I added timer.jquery as NPM and Bower WebJars yet couldnt find it when i searched for it after. Can you check if you are able to see if its added? Do I need to add something to the repo to make it visible on the WebJars site?

**Comment by naXa777** [comment]
Good news: I tried to include the library in my project and it's resolved successfully. So the library is actually deployed to Maven Central repository.
I don't know why it's not searchable via web tools.

Congratulations! =)

---

Example of Gradle build file:

```groovy
dependencies {
    // Webjars Locator allows to use version agnostic URLs for Webjars
    implementation group: 'org.webjars', name: 'webjars-locator-core', version: '0.36'
    // https://jquerytimer.com/
    implementation group: 'org.webjars.bowergithub.walmik', name: 'timer.jquery', version: '0.9.0'
    // ...
}
```

Example of usage:
```html
<script type="text/javascript" src="/webjars/timer.jquery/dist/timer.jquery.min.js"></script>
```
