### ISSUE TITLE
Countdown timer does'nt start again from 0

### ISSUE THREAD

**Issue by subhajeet2107** [walmik/timer.jquery#93]
We want to continue the timer after it reacher 0, in the 0.7.0 version it was working fine but right now it is not working also i can see this functionality was added recently but there is no documentation.
how to continue countdown timer after it reaches 0 ?

**Comment by walmik** [comment]
Hi @subhajeet2107 It would defeat the purpose of a countdown if the timer started again automatically. I m assuming you want to start counting "up" after a countdown is completed. However you can do it by just removing the current timer on the element and then starting it in the callback property that the timer allows. 

```
$('#t').timer({
  duration: '10s',
  countdown: true,
  callback: function() {
    $("#t").timer('remove');
    $('#t').timer();
  }
});
```

[Click here for a JS Bin that demonstrates this](https://jsbin.com/fukogabowu/edit?js,output)

**Comment by subhajeet2107** [comment]
Thanks, earlier a recent pull request added this functionality by default, but it was not working in the latest version.
This will work for now, but if we could add a flag that added the asked functionality it would be great, for example set a flag countUpAfterDone:true, this will allow countdown to counting up from 0 after countdown finishes.
callback also works
